# Enable AndroidX and Jetifier
android.useAndroidX=true
android.enableJetifier=true

# Suppress compileSdk warning for newer Android SDKs
android.suppressUnsupportedCompileSdk=36

# Optimasi memori JVM dan build speed
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# Android modern configuration
android.nonTransitiveRClass=true
